# Generated by Django 5.2.1 on 2025-05-27 10:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='descriptiom',
            new_name='description',
        ),
    ]
